### ISSUE TITLE
Create User table

### ISSUE THREAD

**Issue by alm0st907** [alm0st907/codecon-422#24]
Create the user table, and ideally create authentication.

Should have these fields, any others deemed necessary as time goes on. 

Likely need to work with Jeff for the authentication if we have the ability to get that in. Look at OAuth is my suggestion.

- User name
- email
- associated projects
- some sort of ID

**Comment by bergerMichael** [comment]
User to project is a one-to-many relationship. The way to represent this in sql is to create a foreign key on the many side of the relationship linking back to the "one" side. To do this it would make the most sense if Task assignees are foreign keys linked to users.
