### ISSUE TITLE
Setup SQL Express or comparable database stub

### ISSUE THREAD

**Issue by alm0st907** [alm0st907/codecon-422#5]
We can pivot if needed, want optimal solution rather than a specific blind commit to a tech.

**Comment by bergerMichael** [comment]
I'm pretty close o n this, I just need to point the SQL server to a data directory within the project repository.

**Comment by bergerMichael** [comment]
I attempted this solution but to no avail. Instead I've created the database on my server along with ll tables and I'm going to back the database up with instructions to restore it in the readme. I am having some issues with user permissions in the server that I will resolve soon.
